**This notebook is an exercise in the [Intermediate Machine Learning](https://www.kaggle.com/learn/intermediate-machine-learning) course.  You can reference the tutorial at [this link](https://www.kaggle.com/alexisbcook/introduction).**

---

As a warm-up, you'll review some machine learning fundamentals and submit your initial results to a Kaggle competition.

# Setup

The questions below will give you feedback on your work. Run the following cell to set up the feedback system.

In [1]:
# Set up code checking
import os
if not os.path.exists("../input/train.csv"):
    os.symlink("../input/home-data-for-ml-course/train.csv", "../input/train.csv")  
    os.symlink("../input/home-data-for-ml-course/test.csv", "../input/test.csv")  
from learntools.core import binder
binder.bind(globals())
from learntools.ml_intermediate.ex1 import *
print("Setup Complete")

Setup Complete

You will work with data from the [Housing Prices Competition for Kaggle Learn Users](https://www.kaggle.com/c/home-data-for-ml-course) to predict home prices in Iowa using 79 explanatory variables describing (almost) every aspect of the homes.  

![Ames Housing dataset image](https://storage.googleapis.com/kaggle-media/learn/images/lTJVG4e.png)

Run the next code cell without changes to load the training and validation features in `X_train` and `X_valid`, along with the prediction targets in `y_train` and `y_valid`.  The test features are loaded in `X_test`.  (_If you need to review **features** and **prediction targets**, please check out [this short tutorial](https://www.kaggle.com/dansbecker/your-first-machine-learning-model).  To read about model **validation**, look [here](https://www.kaggle.com/dansbecker/model-validation).  Alternatively, if you'd prefer to look through a full course to review all of these topics, start [here](https://www.kaggle.com/learn/machine-learning).)_

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

# Read the data
X_full = pd.read_csv('../input/train.csv', index_col='Id')
X_test_full = pd.read_csv('../input/test.csv', index_col='Id')

# Obtain target and predictors
y = X_full.SalePrice
features = ['LotArea', 'YearBuilt', '1stFlrSF', '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']
X = X_full[features].copy()
X_test = X_test_full[features].copy()

# Break off validation set from training data
X_train, X_valid, y_train, y_valid = train_test_split(X, y, train_size=0.8, test_size=0.2,
                                                      random_state=0)

Use the next cell to print the first several rows of the data. It's a nice way to get an overview of the data you will use in your price prediction model.

In [3]:
X_train.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
Id,,,,,,,
619,11694,2007,1828,0,2,3,9
871,6600,1962,894,0,1,2,5
93,13360,1921,964,0,1,2,5
818,13265,2002,1689,0,2,3,7
303,13704,2001,1541,0,2,3,6

The next code cell defines five different random forest models.  Run this code cell without changes.  (_To review **random forests**, look [here](https://www.kaggle.com/dansbecker/random-forests)._)

In [4]:
from sklearn.ensemble import RandomForestRegressor

# Define the models
model_1 = RandomForestRegressor(n_estimators=50, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, random_state=0)
model_3 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', random_state=0)
model_4 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)
model_5 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)

models = [model_1, model_2, model_3, model_4, model_5]

To select the best model out of the five, we define a function `score_model()` below.  This function returns the mean absolute error (MAE) from the validation set.  Recall that the best model will obtain the lowest MAE.  (_To review **mean absolute error**, look [here](https://www.kaggle.com/dansbecker/model-validation).)_

Run the code cell without changes.

In [5]:
from sklearn.metrics import mean_absolute_error

# Function for comparing different models
def score_model(model, X_t=X_train, X_v=X_valid, y_t=y_train, y_v=y_valid):
    model.fit(X_t, y_t)
    preds = model.predict(X_v)
    return mean_absolute_error(y_v, preds)

for i in range(0, len(models)):
    mae = score_model(models[i])
    print("Model %d MAE: %d" % (i+1, mae))

Model 1 MAE: 24015
Model 2 MAE: 23740
Model 3 MAE: 23528
Model 4 MAE: 23996
Model 5 MAE: 23706

# Step 1: Evaluate several models

Use the above results to fill in the line below.  Which model is the best model?  Your answer should be one of `model_1`, `model_2`, `model_3`, `model_4`, or `model_5`.

In [6]:
# Fill in the best model
best_model = model_3

# Check your answer
step_1.check()

Correct

In [7]:
# Lines below will give you a hint or solution code
#step_1.hint()
#step_1.solution()

# Step 2: Generate test predictions

Great. You know how to evaluate what makes an accurate model. Now it's time to go through the modeling process and make predictions. In the line below, create a Random Forest model with the variable name `my_model`.

It was said that...

```python
from sklearn.ensemble import RandomForestRegressor

# Define the models
model_1 = RandomForestRegressor(n_estimators=50, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, random_state=0)
model_3 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', random_state=0)
model_4 = RandomForestRegressor(n_estimators=200, min_samples_split=20, random_state=0)
model_5 = RandomForestRegressor(n_estimators=100, max_depth=7, random_state=0)
```

https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestRegressor.html

- min_samples_split (default is 2) : The minimum number of samples required to split an internal node:
- max_leaf_nodes: (int), default=None Grow trees with max_leaf_nodes in best-first fashion. Best nodes are defined as relative reduction in impurity. If None then unlimited number of leaf nodes.
- n_estimators: (int), default=100 The number of trees in the forest.
- max_features : ({“sqrt”, “log2”, None}, int or float, default=1.0) The number of features to consider when looking for the best split:
    - If int, then consider max_features features at each split.
    - If float, then max_features is a fraction and max(1, int(max_features * n_features_in_)) features are considered at each split.
    - If “sqrt”, then max_features=sqrt(n_features).
    - If “log2”, then max_features=log2(n_features).
    - If None or 1.0, then max_features=n_features.
- min_samples_leaf: int or float, default=1 The minimum number of samples required to be at a leaf node. A split point at any depth will only be considered if it leaves at least min_samples_leaf training samples in each of the left and right branches. This may have the effect of smoothing the model, especially in regression.
    - If int, then consider min_samples_leaf as the minimum number.
    - If float, then min_samples_leaf is a fraction and ceil(min_samples_leaf * n_samples) are the minimum number of samples for each node.
- max_depth(int, default=None): The maximum depth of the tree. If None, then nodes are expanded until all leaves are pure or until all leaves contain less than min_samples_split samples.

In [8]:
def val_score(model, X_v=X_valid, y_v=y_valid):
    preds = model.predict(X_v)
    return mean_absolute_error(y_v, preds)

def self_score(model, X_t=X_train, y_t=y_train):
    return mean_absolute_error(y_t, model.predict(X_t))

In [9]:
print(X_train.shape, X_valid.shape)

(1168, 7) (292, 7)

#### Experiment 1

In [10]:
model_1 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=2, random_state=0)
model_2 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=4, random_state=0)
model_3 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=10, random_state=0)
model_4 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=20, random_state=0)
model_5 = RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=50, random_state=0)

In [11]:
models = [model_1, model_2, model_3, model_4, model_5]
rows = []

for model in models:
    model.fit(X_train, y_train)
    rows.append({
        'self_score': self_score(model),
        'val_score': val_score(model)
    })

score = pd.DataFrame(rows)
score

     self_score     val_score
0   8543.640967  23528.784212
1   9952.632196  23522.256473
2  13626.545514  23557.791678
3  17089.320390  24103.301473
4  21647.483647  25720.297226

min_samples_split=4 (2: not bad, 10: not so good)


#### Experiment 2

In [12]:
models = []
models.append(RandomForestRegressor(n_estimators=20, criterion='absolute_error', min_samples_split=2, random_state=0))
models.append(RandomForestRegressor(n_estimators=50, criterion='absolute_error', min_samples_split=2, random_state=0))
models.append(RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=2, random_state=0))
models.append(RandomForestRegressor(n_estimators=200, criterion='absolute_error', min_samples_split=2, random_state=0))
models.append(RandomForestRegressor(n_estimators=20, criterion='absolute_error', min_samples_split=4, random_state=0))
models.append(RandomForestRegressor(n_estimators=50, criterion='absolute_error', min_samples_split=4, random_state=0))
models.append(RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=4, random_state=0))
models.append(RandomForestRegressor(n_estimators=200, criterion='absolute_error', min_samples_split=4, random_state=0))
models.append(RandomForestRegressor(n_estimators=20, criterion='absolute_error', min_samples_split=20, random_state=0))
models.append(RandomForestRegressor(n_estimators=50, criterion='absolute_error', min_samples_split=20, random_state=0))
models.append(RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=20, random_state=0))
models.append(RandomForestRegressor(n_estimators=200, criterion='absolute_error', min_samples_split=20, random_state=0))
models.append(RandomForestRegressor(n_estimators=20, criterion='absolute_error', min_samples_split=50, random_state=0))
models.append(RandomForestRegressor(n_estimators=50, criterion='absolute_error', min_samples_split=50, random_state=0))
models.append(RandomForestRegressor(n_estimators=100, criterion='absolute_error', min_samples_split=50, random_state=0))
models.append(RandomForestRegressor(n_estimators=200, criterion='absolute_error', min_samples_split=50, random_state=0))

In [13]:
rows = []

for model in models:
    model.fit(X_train, y_train)
    depths = [tree.get_depth() for tree in model.estimators_]
    nodes = [tree.tree_.node_count for tree in model.estimators_]
    rows.append({
        'self_score': self_score(model),
        'val_score': val_score(model),
        'avg_depth': sum(depths) / len(depths),
        'avg node #': sum(nodes) / len(nodes)
    })

score = pd.DataFrame(rows)
score

      self_score     val_score  avg_depth  avg node #
0    9426.731293  23832.719007     24.550     1387.80
1    8623.280788  23582.153425     24.340     1391.48
2    8543.640967  23528.784212     24.750     1394.54
3    8460.169617  23426.574007     24.670     1394.11
4   10593.319799  23979.533904     22.850      786.60
5    9979.961772  23761.994384     22.700      788.96
6    9952.632196  23522.256473     23.060      791.54
7    9832.054182  23512.654015     22.865      792.40
8   17409.294307  23823.113613     15.650      169.70
9   17110.859435  24272.907979     15.640      170.92
10  17089.320390  24103.301473     15.950      173.92
11  16978.354334  24039.888031     15.790      174.36
12  22188.214148  25894.647945     10.200       62.20
13  21608.924341  25813.779658     10.280       63.48
14  21647.483647  25720.297226     10.470       63.40
15  21767.769576  25671.570719     10.360       61.88

"Suggestion: min_sample_split=2 is the best"

#### Experiment 3

Running this is recommended to be skipped for performance issues.

In [14]:
from itertools import product
from sklearn.ensemble import RandomForestRegressor

n_estimators_list = [20, 50, 100, 200]
min_samples_split_list = [2]
max_depth_list = [None, 10, 16, 24]
min_samples_leaf_list = [1, 5, 10]
max_features_list = ['sqrt', 0.5, None]

models = []

for params in product(
    n_estimators_list,
    min_samples_split_list,
    max_depth_list,
    min_samples_leaf_list,
    max_features_list
):
    n_estimators, min_split, max_depth, min_leaf, max_feat = params

    models.append(
        RandomForestRegressor(
            n_estimators=n_estimators,
            min_samples_split=min_split,
            max_depth=max_depth,
            min_samples_leaf=min_leaf,
            max_features=max_feat,
            criterion='absolute_error',
            random_state=0
        )
    )

In [15]:
rows = []

for model in models:
    model.fit(X_train, y_train)
    depths = [tree.get_depth() for tree in model.estimators_]
    nodes = [tree.tree_.node_count for tree in model.estimators_]
    rows.append({
        'self_score': self_score(model),
        'val_score': val_score(model),
        'avg_depth': sum(depths) / len(depths),
        'avg node #': sum(nodes) / len(nodes)
    })

score = pd.DataFrame(rows)
score

       self_score     val_score  avg_depth  avg node #
0     9764.377440  24196.103596     24.300     1333.90
1     9210.002911  24233.000000     23.750     1384.60
2     9426.731293  23832.719007     24.550     1387.80
3    19831.168557  25708.739897     12.700      188.70
4    18910.434268  24705.280051     13.050      205.00
..            ...           ...        ...         ...
139  18192.843234  24683.792380     13.160      209.95
140  17088.717468  23928.182354     13.205      216.34
141  22191.948358  26419.864606     10.135       99.16
142  21267.957301  26060.697423     10.420      107.40
143  20026.176066  24607.745462     10.495      109.74

[144 rows x 4 columns]

In [16]:
score.val_score.describe()

count      144.000000
mean     24714.888574
std       1086.463435
min      23070.828596
25%      23758.395796
50%      24607.745462
75%      25337.538964
max      27046.535188
Name: val_score, dtype: float64

In [17]:
indices = []

for (i, yes) in enumerate(score.val_score<23500):
    if yes: indices.append(i)
print(len(indices), indices)

14 [11, 45, 47, 65, 82, 83, 92, 100, 110, 118, 119, 128, 136, 137]

In [18]:
L1 = len(n_estimators_list)      # 4
L2 = len(max_depth_list)         # 4
L3 = len(min_samples_leaf_list)  # 3
L4 = len(max_features_list)      # 3

def decode_index(idx):
    f_idx = idx % L4
    idx //= L4
    
    leaf_idx = idx % L3
    idx //= L3
    
    depth_idx = idx % L2
    idx //= L2
    
    est_idx = idx % L1

    return {
        "n_estimators": n_estimators_list[est_idx],
        "max_depth": max_depth_list[depth_idx],
        "min_samples_leaf": min_samples_leaf_list[leaf_idx],
        "max_features": max_features_list[f_idx],
    }

decoded = [decode_index(i) for i in indices]

In [19]:
import pandas as pd

df = pd.DataFrame(decoded)

df.value_counts(dropna=False)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()

n_estimators  max_depth  min_samples_leaf  max_features
20            10.0       1                 NaN             1
50            10.0       1                 sqrt            1
                                           NaN             1
              24.0       1                 NaN             1
100           10.0       1                 0.5             1
                                           NaN             1
              16.0       1                 NaN             1
              24.0       1                 0.5             1
200           10.0       1                 0.5             1
                                           NaN             1
              16.0       1                 NaN             1
              24.0       1                 0.5             1
                                           NaN             1
              NaN        1                 NaN             1
Name: count, dtype: int64

In [20]:
df['max_depth'].value_counts(dropna=False)

max_depth
10.0    7
24.0    4
16.0    2
NaN     1
Name: count, dtype: int64

In [21]:
df['min_samples_leaf'].value_counts(dropna=False)

min_samples_leaf
1    14
Name: count, dtype: int64

In [22]:
df['max_features'].value_counts(dropna=False)

max_features
None    9
0.5     4
sqrt    1
Name: count, dtype: int64

In [23]:
df['n_estimators'].value_counts(dropna=False)

n_estimators
200    6
100    4
50     3
20     1
Name: count, dtype: int64

Insights:
- min_samples_leaf: 1 (default)
- max_features: None
- max_depth: 10
- n_estimators: 200

In [24]:
# Best model:
best_idx = score['self_score'].idxmin()
print(best_idx)
print(decode_index(best_idx))

110
{'n_estimators': 200, 'max_depth': None, 'min_samples_leaf': 1, 'max_features': None}

#### Experiment 4

In [25]:
# model_0 = RandomForestRegressor(n_estimators=200, min_samples_split=2, max_depth=None,
#             min_samples_leaf=1,
#             max_features=None,
#             criterion='absolute_error',
#             random_state=0
#         )
# model_1 = RandomForestRegressor(n_estimators=200, min_samples_split=2, max_depth=10,
#             min_samples_leaf=1,
#             max_features=None,
#             criterion='absolute_error',
#             random_state=0)

# max_depth_list

models=[]

for depth in max_depth_list:
    models.append(RandomForestRegressor(
        n_estimators=200, min_samples_split=2, max_depth=depth,
            min_samples_leaf=1,
            max_features=None,
            criterion='absolute_error',
            random_state=0
        ))

In [26]:
rows = []

for model in models:
    model.fit(X_train, y_train)
    depths = [tree.get_depth() for tree in model.estimators_]
    nodes = [tree.tree_.node_count for tree in model.estimators_]
    rows.append({
        'self_score': self_score(model),
        'val_score': val_score(model),
        'avg_depth': sum(depths) / len(depths),
        'avg node #': sum(nodes) / len(nodes)
    })

score = pd.DataFrame(rows)
score

     self_score     val_score  avg_depth  avg node #
0   8460.169617  23426.574007     24.670     1394.11
1  11892.537070  23192.578570     10.000      574.61
2   8875.458806  23431.893562     16.000     1227.79
3   8462.805103  23361.294092     23.385     1389.59

Let's pick this:

```python

model_1 = RandomForestRegressor(n_estimators=200, min_samples_split=2, max_depth=10,
min_samples_leaf=1,
max_features=None,
criterion='absolute_error',
random_state=0)

```

In [27]:
# Define a model
my_model = RandomForestRegressor(n_estimators=200, min_samples_split=2, max_depth=10,
min_samples_leaf=1,
max_features=None,
criterion='absolute_error',
random_state=0)

In [28]:
# Check your answer
step_2.check()

Correct

In [29]:
# Lines below will give you a hint or solution code
#step_2.hint()
#step_2.solution()

Run the next code cell without changes.  The code fits the model to the training and validation data, and then generates test predictions that are saved to a CSV file.  These test predictions can be submitted directly to the competition!

In [30]:
# Fit the model to the training data
my_model.fit(X, y)

# Generate test predictions
preds_test = my_model.predict(X_test)

# Save predictions in format used for competition scoring
output = pd.DataFrame({'Id': X_test.index,
                       'SalePrice': preds_test})
output.to_csv('submission.csv', index=False)

# Submit your results

Once you have successfully completed Step 2, you're ready to submit your results to the leaderboard!  First, you'll need to join the competition if you haven't already.  So open a new window by clicking on [this link](https://www.kaggle.com/c/home-data-for-ml-course).  Then click on the **Join Competition** button.  _(If you see a "Submit Predictions" button instead of a "Join Competition" button, you have already joined the competition, and don't need to do so again.)_

Next, follow the instructions below:
1. Begin by clicking on the **Save Version** button in the top right corner of the window.  This will generate a pop-up window.  
2. Ensure that the **Save and Run All** option is selected, and then click on the **Save** button.
3. This generates a window in the bottom left corner of the notebook.  After it has finished running, click on the number to the right of the **Save Version** button.  This pulls up a list of versions on the right of the screen.  Click on the ellipsis **(...)** to the right of the most recent version, and select **Open in Viewer**.  This brings you into view mode of the same page. You will need to scroll down to get back to these instructions.
4. Click on the **Data** tab near the top of the screen.  Then, click on the file you would like to submit, and click on the **Submit** button to submit your results to the leaderboard.

You have now successfully submitted to the competition!

If you want to keep working to improve your performance, select the **Edit** button in the top right of the screen. Then you can change your code and repeat the process. There's a lot of room to improve, and you will climb up the leaderboard as you work.

# Keep going

You've made your first model. But how can you quickly make it better?

Learn how to improve your competition results by incorporating columns with **[missing values](https://www.kaggle.com/alexisbcook/missing-values)**.

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intermediate-machine-learning/discussion) to chat with other learners.*